# Generated by Django 5.1.15 on 2026-03-29 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_add_approx_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneproject',
            name='ai_analysis_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='droneproject',
            name='ai_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='droneproject',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='droneproject',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('queued', 'Queued'), ('preprocessing', 'Preprocessing'), ('processing', 'Processing'), ('analyzing', 'AI Analysis'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploading', max_length=20),
        ),
        migrations.CreateModel(
            name='GeoAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('structure', 'Structure'), ('vehicle', 'Vehicle'), ('lz', 'Landing Zone'), ('obstacle', 'Obstacle'), ('poi', 'Point of Interest'), ('threat', 'Threat'), ('route_wp', 'Route Waypoint')], db_index=True, default='poi', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ai', 'AI Detected'), ('manual', 'Manual'), ('tak', 'TAK Import'), ('external', 'External Import')], db_index=True, default='manual', max_length=20)),
                ('cot_uid', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='processing.droneproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
