# Generated by Django 5.1.15 on 2026-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_droneproject_ai_analysis_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneproject',
            name='ai_enhance_mode',
            field=models.CharField(choices=[('off', 'Off'), ('standard', 'Standard (Sharpen + Contrast)'), ('super_res', 'Super Resolution (AI Upscale)')], default='off', max_length=10),
        ),
    ]
