# Generated by Django 5.1.15 on 2026-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_add_ai_enhance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneproject',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
